### ISSUE TITLE
Not working within Proxmox 7 - KeyError: 'TARFILE'

### ISSUE THREAD

**Issue by mattjes04** [farthinder/Proxmox-Encrypted-Remote-Backup#7]
Upgraded to Proxmox 7 and backup is failing with an error: `INFO: KeyError: 'TARFILE'`

Reason: "Hookscript: The TARFILE environment variable was deprecated in Proxmox VE 6, in favor of TARGET. In Proxmox VE 7, it has been removed entirely and thus, it is not exported to the hookscript anymore." (https://pve.proxmox.com/wiki/Roadmap)

Solution: Change **ProxmoxEventHandler.py** line #153 from `tarfile = os.environ["TARFILE"]` to `tarfile = os.environ["TARGET"]`

Now its working again

**Comment by mattjes04** [comment]
Used an old version, sorry! It's fixed already!

**Comment by farthinder** [comment]
Happy it works for you :)
